-- MySQL Script generated by MySQL Workbench
-- Tue Oct 17 09:13:25 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema pharma
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema pharma
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `pharma` ;
USE `pharma` ;

-- -----------------------------------------------------
-- Table `pharma`.`staff`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `pharma`.`staff` (
  `idstaff` INT AUTO_INCREMENT,
  `email` VARCHAR(45) NOT NULL,
  `password` VARCHAR(255) NOT NULL,
  `role` VARCHAR(45) NOT NULL DEFAULT 'guest',
  `name` VARCHAR(45) NOT NULL,
  `validationCode` VARCHAR(45) NOT NULL,
  `activationStatus` TINYINT(1) NULL DEFAULT 0,
  PRIMARY KEY (`idstaff`),
  UNIQUE INDEX `idstaff_UNIQUE` (`idstaff` ASC) VISIBLE,
  UNIQUE INDEX `email_UNIQUE` (`email` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `pharma`.`suppliers`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `pharma`.`suppliers` (
  `idprovider` INT AUTO_INCREMENT,
  `companyname` VARCHAR(45) NOT NULL,
  `providerImage` VARCHAR(255) NULL,
  `email` VARCHAR(45) NULL,
  `phoneNumber` VARCHAR(45) NULL,
  PRIMARY KEY (`idprovider`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `pharma`.`stock`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `pharma`.`stock` (
  `productName` VARCHAR(45) NULL,
  `activeIngredient` VARCHAR(45) NULL,
  `type` VARCHAR(45) NULL,
  `price` VARCHAR(45) NULL,
  `prescOnly` TINYINT(1) NOT NULL DEFAULT 0,
  `qty` INT NULL DEFAULT 1,
  `expires` VARCHAR(45) NULL,
  `productImage` VARCHAR(255) NULL,
  `refrigerate` TINYINT(1) NULL DEFAULT 0,
  `providers` INT NULL,
  INDEX `providers_idx` (`providers` ASC) VISIBLE,
  UNIQUE INDEX `productName_UNIQUE` (`productName` ASC) VISIBLE,
  CONSTRAINT `providers`
    FOREIGN KEY (`providers`)
    REFERENCES `pharma`.`suppliers` (`idprovider`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `pharma`.`sales`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `pharma`.`sales` (
  `productName` VARCHAR(45) NOT NULL,
  `date` VARCHAR(45) NULL)

ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `pharma`.`deletedsuppliers`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `pharma`.`deletedsuppliers` (
  `iddprovider` INT NOT NULL,
  `companyname` VARCHAR(45) NOT NULL,
  `providerImage` VARCHAR(255) NULL,
  `email` VARCHAR(45) NULL,
  `phoneNumber` VARCHAR(45) NULL,
  PRIMARY KEY (`iddprovider`))
ENGINE = InnoDB;

-- -----------------------------------------------------
-- Table `pharma`.`deletedstock`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `pharma`.`deletedstock` (
  `productName` VARCHAR(45) NULL,
  `activeIngredient` VARCHAR(45) NULL,
  `type` VARCHAR(45) NULL,
  `price` VARCHAR(45) NULL,
  `prescOnly` TINYINT(1) NOT NULL DEFAULT 0,
  `qty` INT NULL DEFAULT 0,
  `expires` VARCHAR(45) NULL,
  `productImage` VARCHAR(255) NULL,
  `refrigerate` TINYINT(1) NULL DEFAULT 0,
  `deletedproviders` INT NULL
)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
